// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY9GGPaAh_3NCGmNCXGdFpYz0ZwYtEuZY',
    appId: '1:629842451420:web:9c1fb85e27086b75d5cd19',
    messagingSenderId: '629842451420',
    projectId: 'flash-chat-e7882',
    authDomain: 'flash-chat-e7882.firebaseapp.com',
    storageBucket: 'flash-chat-e7882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXz3b7qxJBe1b2IZx1goecrLEE50wTU4',
    appId: '1:629842451420:android:f7ddb7f8a863d093d5cd19',
    messagingSenderId: '629842451420',
    projectId: 'flash-chat-e7882',
    storageBucket: 'flash-chat-e7882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBj2Va7VHEluKF1engnvv-LK2DUrO9Aro',
    appId: '1:629842451420:ios:6dbd6133d3286c22d5cd19',
    messagingSenderId: '629842451420',
    projectId: 'flash-chat-e7882',
    storageBucket: 'flash-chat-e7882.appspot.com',
    iosClientId: '629842451420-gqjd508d1ui5npufbrde51tmdjg8pd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBj2Va7VHEluKF1engnvv-LK2DUrO9Aro',
    appId: '1:629842451420:ios:6dbd6133d3286c22d5cd19',
    messagingSenderId: '629842451420',
    projectId: 'flash-chat-e7882',
    storageBucket: 'flash-chat-e7882.appspot.com',
    iosClientId: '629842451420-gqjd508d1ui5npufbrde51tmdjg8pd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerFoodDelivery',
  );
}
